### ISSUE TITLE
Plugin Update for 5.4 when?

### ISSUE THREAD

**Issue by saravanan290702** [StudioSyndiCatCaius/OmegaGameFramework#16]
when will the plugin be updated for unreal engine 5.4? thank you

**Comment by HeadClot** [comment]
Hey @saravanan290702 Check the [releases ](https://github.com/StudioSyndiCatCaius/OmegaGameFramework/releases/tag/v1.4) section.

**Comment by saravanan290702** [comment]
ah thankyou for the update
